#!/bin/bash
# Get infos from the current loaded activity

[ -n "$userspace" ] || exit 1

activity.id(){
    cat "$userspace/activity.id" 2> /dev/null   
}

activity.name(){
    cat "$userspace/activity.name" 2> /dev/null   
}

activity.desc(){
    cat "$userspace/activity.desc" 2> /dev/null 
}

activity.icon(){
    cat "$userspace/activity.icon" 2> /dev/null 
}

activity.check(){
    cat "$userspace/activity.check" 2> /dev/null
}

activity.pid(){
    cat "$userspace/activity.pid" 2> /dev/null
}

# Activity root path
activity.path(){
    local actname=`activity.name`
    [ -n "$actname" ] || return
    printf "$activities/%s" $actname
}

# Has a .keys file
activity.haskeys(){
    local actname=`activity.name`
    [ -n "$actname" ] || return 1
    test -r "`activity.path`/$actname.keys"
    return $?
}

# Last pushed key
activity.key(){
    cat "$userspace/activity.key" 2> /dev/null
}

#checks if activity exists
activity.exists(){
    [ -n "$1" ] || return 1
    cmd test -r "$activities/$1/$1.conf"
    return $?
}