#!/bin/bash
# Get infos from the current loaded activity

[ -n "$userspace" ] || exit 1

activity.id(){
    cat "$userspace/activity.id" 2> /dev/null   
}

activity.name(){
    cat "$userspace/activity.name" 2> /dev/null   
}

activity.desc(){
    cat "$userspace/activity.desc" 2> /dev/null 
}

activity.icon(){
    cat "$userspace/activity.icon" 2> /dev/null 
}

activity.check(){
    cat "$userspace/activity.check" 2> /dev/null
}

activity.pid(){
    cat "$userspace/activity.pid" 2> /dev/null
}

activity.send(){
    [ -n "$1" ] || return 1
    activity.haskeys || return 1
    pushd `activity.path` > /dev/null 2>&1
    bash `activity.id`.keys $1
    local ret=$?
    popd > /dev/null 2>&1
    return $ret
}

# Activity root path
activity.path(){
    local actname=`activity.id`
    [ -n "$actname" ] || return
    printf "$activities/%s" $actname
}

# Has a .keys file
activity.haskeys(){
    local actname=`activity.id`
    [ -n "$actname" ] || return 1
    test -r "`activity.path`/$actname.keys"
    return $?
}


#checks if activity exists
activity.exists(){
    [ -n "$1" ] || return 1
    cmd test -r "$activities/$1/$1.conf"
    return $?
}