#!/bin/bash
# Get infos from the current loaded activity

[ -n "$userspace" ] || exit 1

activity(){
    activity.name

}

activity.name(){
    printf ""
    [ -r "$userspace/activity.name" ] || return
    cat "$userspace/activity.name"
}

activity.desc(){
    printf ""
    [ -r "$userspace/activity.desc" ] || return
    cat "$userspace/activity.desc"
}

activity.icon(){
    printf ""
    [ -r "$userspace/activity.icon" ] || return
    cat "$userspace/activity.icon"
}

activity.pid(){
    printf ""
    [ -r "$userspace/activity.pid" ] || return
    cat "$userspace/activity.pid"
}
