#!/bin/bash
# Detects if flirc device is connected and 
# launch LIRC, then if Harmony Daemon is running
# Notify it

[ -r /etc/default/harmony ] || exit 0
. /etc/default/harmony
. $prefix/usr/lib/harmony/utils

lirc=lircd
pidfile=/var/run/flircd.pid

[ "$(id -u)" != "0" ] && throw_error "This script can only be run by root user."

if ! echo $@ | grep -q "\-d" && [ ! -e $pidfile ]; then
    $0 --daemon &
    exit 0
fi

[ -e $pidfile ] && exit 2
pgrep -f -n $0 > $pidfile

on_signal(){
    killall -10 harmonyd
}


on_start(){
    [ -d "/run/lirc" ] || mkdir -p "/run/lirc"
    cmd $lirc -d $device &
    cmd ln -fs /run/lirc/lircd /dev/lircd
    trigger signal
}

on_stop(){
    cmd killall $lirc
    trigger signal
}

on_reload(){
    cmd killall -1 $lirc
}


on_check(){
    if [ -z "$(get_device)" ]; then
        cmd pidof $lirc && trigger stop
        return 1
    fi
    cmd pidof $lirc || trigger start
}


on_kill(){
    exit 0
}

on_exit(){
    cmd pidof $lirc && trigger stop
    cmd rm $pidfile
}

# Starting daemon
trap on_exit EXIT
trap on_kill SIGINT SIGTERM SIGQUIT 
trap on_reload SIGHUP


while true; do
    trigger check
	sleep 10
done