#!/bin/bash
# Detects if flirc device is connected and 
# launch LIRC, then if Harmony Daemon is running
# Notify it

[ -r /etc/default/harmony ] || exit 0
. /etc/default/harmony
. $prefix/usr/lib/harmony/utils

lirc=lircd
pidfile=/var/run/flircd.pid

[ "$(id -u)" != "0" ] && throw_error "This script can only be run by root user."

if ! echo $@ | grep -q "\-\-daemon" && [ ! -e $pidfile ]; then
    $0 --daemon &
    exit 0
fi

[ -e $pidfile ] && exit 2
pgrep -f -n $0 > $pidfile

do_signal(){
    cmd killall -10 harmony
}


do_start(){
    [ -d "/run/lirc" ] || mkdir -p "/run/lirc"
    cmd $lirc -d $device &
    cmd ln -fs /run/lirc/lircd /dev/lircd
    do_signal
}

do_stop(){
    cmd killall $lirc
    do_signal
}

do_reload(){
    cmd killall -1 $lirc
}


do_check(){
    if [ -z "$(get_device)" ]; then
        cmd pidof $lirc && do_stop
        return 1
    fi
    cmd pidof $lirc || do_start
}


do_kill(){
    exit 0
}

do_exit(){
    cmd pidof $lirc && do_stop
    cmd rm $pidfile
}

# Starting daemon
trap do_exit EXIT
trap do_kill SIGINT SIGTERM SIGQUIT 
trap do_reload SIGHUP


while true; do
    do_check
	sleep 10
done