#!/bin/sh
### BEGIN INIT INFO
# Provides:          flircd
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts the FLIRC daemon.
# Description:       Detects FLIRC and launch LIRC.
### END INIT INFO


# source generic LSB initscript helpers
. /lib/lsb/init-functions

# check if the lirc package is still installed and this not a stale conffile
test -x /usr/sbin/lircd  || exit 0
test -r /etc/default/harmony || exit 0
. /etc/default/harmony

name="flircd"
description="remote control daemon"
daemon=$prefix/sbin/$name
pidfile=/var/run/$name.pid

do_start(){
	if ! pidof -x $name > /dev/null 2>&1; then
		rm $pidfile > /dev/null 2>&1
		$daemon --daemon &
		while [ ! -e $pidfile ]; do
			sleep 1
		done
	fi
}
do_stop(){
	[ -e $pidfile ] || return 0
	kill "$(cat $pidfile)"
	while [ -e $pidfile ]; do
		sleep 1
	done
	return 0
}
do_restart(){
	do_stop
	do_start
}


case "$1" in
	start)
		log_daemon_msg "Starting $description" "$name"
		do_start
		log_end_msg $?
		;;
	stop)
		log_daemon_msg "Stopping $description" "$name"
		do_stop
		log_end_msg $?
		;;
	reload|force-reload)
		do_restart &
		log_end_msg 0
		;;
	restart)
		do_restart &
	;;
	status)
		pidof -x $name > /dev/null 2>&1 && log_success_msg "$name is running" && exit 0
		log_failure_msg "$name is not running" && exit 3
		;;
	*)
		echo "Usage: /etc/init.d/flirc {start|stop|reload|restart|force-reload|status}"
		exit 1
		;;
esac

exit 0
