#!/bin/sh
### BEGIN INIT INFO
# Provides:          flirc
# Required-Start:    $local_fs $remote_fs $syslog
# Required-Stop:     $local_fs $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts the FLIRC daemon.
# Description:       Detects FLIRC and launch LIRC who is used to control different
#                    infrared receivers and transceivers.
### END INIT INFO


# source generic LSB initscript helpers
. /lib/lsb/init-functions

# check if the lirc package is still installed and this not a stale conffile
test -x /usr/sbin/lircd  || exit 0

name="flirc"
description="remote control daemon"

test -r /etc/default/harmony || exit 0
. /etc/default/harmony

daemon=$prefix/sbin/flirc
pidfile=/var/run/flirc.pid

case "$1" in
	start)
		log_daemon_msg "Starting $description" "$name"
		if ! pidof -x $daemon > /dev/null 2>&1; then
			rm $pidfile > /dev/null 2>&1
			start-stop-daemon --quiet --start --exec $daemon -- --daemon
			log_end_msg $?
		fi
		log_end_msg 0
		;;
	stop)
		log_daemon_msg "Stopping $description" "$name"
		status=0
		for pid in $(pidof -x $daemon); do
			kill $pid > /dev/null 2>&1 || status=$?
		done
		log_end_msg $status
		;;
	reload|force-reload)
		log_daemon_msg "Reload configuration for $description" "$name"
		status=0
		for pid in $(pidof -x $daemon); do
			kill -1 $pid > /dev/null 2>&1 || status = $?
		done
		log_end_msg $status
		;;
	restart)
		$0 stop
		$0 start
		;;
	status)
		pidof -x $daemon > /dev/null 2>&1 && log_success_msg "$name is running" && exit 0
		log_failure_msg "$name is not running" && exit 3
		;;
	*)
		echo "Usage: /etc/init.d/flirc {start|stop|reload|restart|force-reload|status}"
		exit 1
		;;
esac

exit 0
