#!/bin/sh
### BEGIN INIT INFO
# Provides:          lircd
# Required-Start:    $local_fs $remote_fs $syslog
# Required-Stop:     $local_fs $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts the LIRCD daemon.
# Description:       LIRC is used to control different
#                    infrared receivers and transceivers.
### END INIT INFO


# source generic LSB initscript helpers
. /lib/lsb/init-functions

# check if the lirc package is still installed and this not a stale conffile
test -x /usr/sbin/lircd  || exit 0

device=$(find /dev/input/ | grep flirc)

case "$1" in
	start)
        [ -z "$device" ] && exit 0
		# start lircd
		[ -d "/run/lirc" ] || mkdir -p "/run/lirc"

		log_daemon_msg "Starting remote control daemon" "FLIRC"
		start-stop-daemon --start --quiet --oknodo --exec /usr/sbin/lircd -- -d $device < /dev/null
		log_end_msg $?

		# retain compatibility with old clients
		ln -fs /run/lirc/lircd /dev/lircd
		;;
	stop)
		log_daemon_msg "Stopping remote control daemon" "FLIRC"
		start-stop-daemon --stop --quiet \
			--exec /usr/sbin/lircd
		log_end_msg $?
		;;
	reload|force-reload)
		log_daemon_msg "Reload configuration for remote control daemon" "FLIRC"
		start-stop-daemon --stop --quiet --signal 1 \
			--exec /usr/sbin/lircd
		log_end_msg $?
		;;
	restart)
		$0 stop
		$0 start
		;;
	status)
		status_of_proc /usr/sbin/lircd lircd   || exit $?
		;;
	*)
		echo "Usage: /etc/init.d/flirc {start|stop|reload|restart|force-reload|status}"
		exit 1
		;;
esac

exit 0
